"""Ingest-layer primitives (RAW-001: content-addressed raw object writer)."""

from __future__ import annotations

from cryptofactors.ingest.raw import (
    AcquisitionMetadata,
    CatalogRegistrationError,
    ChecksumAlgorithm,
    ChecksumError,
    ChecksumVerification,
    CorruptDestinationError,
    FailedAcquisitionRecord,
    HashMismatchError,
    IdempotentDuplicateResult,
    InterruptedWriteError,
    InvalidChunkError,
    OrphanReconciliationReport,
    PathSafetyError,
    ProviderChecksum,
    PublicationError,
    PublicationReceipt,
    PublishResult,
    RawObjectCatalog,
    RawObjectStoreConfig,
    RawObjectWriter,
    RawStoreError,
    RecoverableCatalogRegistrationError,
    SqliteRawObjectCatalog,
    content_addressed_relative_path,
    reconcile_orphan_temps,
)

__all__ = [
    "AcquisitionMetadata",
    "CatalogRegistrationError",
    "ChecksumAlgorithm",
    "ChecksumError",
    "ChecksumVerification",
    "CorruptDestinationError",
    "FailedAcquisitionRecord",
    "HashMismatchError",
    "IdempotentDuplicateResult",
    "InterruptedWriteError",
    "InvalidChunkError",
    "OrphanReconciliationReport",
    "PathSafetyError",
    "ProviderChecksum",
    "PublicationError",
    "PublicationReceipt",
    "PublishResult",
    "RawObjectCatalog",
    "RawObjectStoreConfig",
    "RawObjectWriter",
    "RawStoreError",
    "RecoverableCatalogRegistrationError",
    "SqliteRawObjectCatalog",
    "content_addressed_relative_path",
    "reconcile_orphan_temps",
]
