"""Ingest-layer primitives (RAW-001 raw store + LEG-001 legacy scanner)."""

from __future__ import annotations

from cryptofactors.ingest.legacy_local import (
    ClassificationRule,
    EntryType,
    EvidenceClass,
    ExclusionRule,
    InventoryEntry,
    InventorySummary,
    LegacyInventoryExistsError,
    LegacyLocalScanner,
    LegacyOutputError,
    LegacyPathError,
    LegacyScanError,
    LegacyTraversalError,
    ProvenanceClass,
    ScanConfig,
    ScanStatus,
    scan_legacy_root,
)
from cryptofactors.ingest.raw import (
    AcquisitionConflictError,
    AcquisitionMetadata,
    CatalogRegistrationError,
    ChecksumAlgorithm,
    ChecksumError,
    ChecksumVerification,
    CorruptDestinationError,
    DurabilityError,
    FailedAcquisitionRecord,
    HashMismatchError,
    IdempotentDuplicateResult,
    InterruptedWriteError,
    InvalidChunkError,
    OrphanReconciliationReport,
    PathSafetyError,
    ProviderChecksum,
    PublicationError,
    PublicationReceipt,
    PublishResult,
    RawObjectCatalog,
    RawObjectStoreConfig,
    RawObjectWriter,
    RawStoreError,
    RecoverableCatalogRegistrationError,
    SqliteRawObjectCatalog,
    content_addressed_relative_path,
    reconcile_orphan_temps,
)

__all__ = [
    # RAW-001
    "AcquisitionConflictError",
    "AcquisitionMetadata",
    "CatalogRegistrationError",
    "ChecksumAlgorithm",
    "ChecksumError",
    "ChecksumVerification",
    "CorruptDestinationError",
    "DurabilityError",
    "FailedAcquisitionRecord",
    "HashMismatchError",
    "IdempotentDuplicateResult",
    "InterruptedWriteError",
    "InvalidChunkError",
    "OrphanReconciliationReport",
    "PathSafetyError",
    "ProviderChecksum",
    "PublicationError",
    "PublicationReceipt",
    "PublishResult",
    "RawObjectCatalog",
    "RawObjectStoreConfig",
    "RawObjectWriter",
    "RawStoreError",
    "RecoverableCatalogRegistrationError",
    "SqliteRawObjectCatalog",
    "content_addressed_relative_path",
    "reconcile_orphan_temps",
    # LEG-001
    "ClassificationRule",
    "EntryType",
    "EvidenceClass",
    "ExclusionRule",
    "InventoryEntry",
    "InventorySummary",
    "LegacyInventoryExistsError",
    "LegacyLocalScanner",
    "LegacyOutputError",
    "LegacyPathError",
    "LegacyScanError",
    "LegacyTraversalError",
    "ProvenanceClass",
    "ScanConfig",
    "ScanStatus",
    "scan_legacy_root",
]
